<?php
/**
 * @file
 *   Implement multi-lingual website. 
 *   todo: bring in translation. 
 */
 
/**
 * Implementation of hook_help()
 */
function owhtranslate_help($path, $arg) {
  if ($path == 'admin/help#owhtranslate') {
    $txt = 'Set up multilingual website.';
    $output = t($txt);
    return $output;
  }
}

/**
 * Translate menus from 'all languages' 
 * (the default setting, which is the same as 'neutral')
 * to designated language code.
 * 
 * @param, $mlid
 *  string, menu link id (from menu_link table)
 * 
 * @param $langcode
 *  string, language code
 */
function owhtranslate_menu_lang($mlid, $langcode = 'en') {
  // get menu options from menu_link table
  $options = db_result(db_query("SELECT options FROM {menu_links} WHERE mlid = %d", $mlid));
  $options = unserialize($options);
  // set language code
  if (!$options['langcode']) { // language code hasn't been set, default "all languages"
    $options['langcode'] = $langcode;
    $options = serialize($options);
    // update
    db_query("UPDATE {menu_links} SET options = '%s' where mlid = %d", $options, $mlid);
  }
}

